from processors.image_processor import ImageExtractor, ImageCleaner, RuleBasedCoverSelector, RuleBasedCaptionGenerator, RuleBasedImageMatcher
from processors.vision_processor import VisionLLMClient, VisionImageProcessor
from processors.translator import ArticleTranslator
